### ISSUE TITLE
Removed update_with function is needed

### ISSUE THREAD

**Issue by sonalkr132** [bundler/compact_index#17]
`update_with` function was removed in this commit: https://github.com/bundler/compact_index/commit/b8196ed0bcde002b4251dc768cea56e6fde8452b

Function `parse_gems_for_create` coalesced the gem versions when when `versions.list` file was created. Using current option `create` gives following:
```
yaml_compare 0.1.1 
yaml_compare 0.1.2 
yaml_compare 0.1.3 
yaml_compare 0.1.4 
yaml_compare 0.1.5 
yaml_compare 0.1.6 
```

**Comment by fotanus** [comment]
Creating should not generate one line per gem. We have [this spec](https://github.com/bundler/compact_index/blob/master/spec/versions_file_spec.rb#L44) to assert that.

**Comment by sonalkr132** [comment]
> We have this spec to assert that.

That spec is passing because both [versions are in same array](https://github.com/bundler/compact_index/blob/master/spec/versions_file_spec.rb#L35-L38). [bundler-api](https://github.com/bundler/bundler-api/blob/master/lib/bundler_api/gem_info.rb#L94-L102) or [rubygems.org](https://github.com/rubygems/rubygems.org/blob/master/app/models/rubygem.rb#L380-L388) don't provide versions info in that form. They generate versions info in format:
```Ruby
[CompactIndex::Gem.new('foo', [CompactIndex::GemVersion.new('1.0.1', 'ruby', nil, '32ddwe')]),
 CompactIndex::Gem.new('foo', [CompactIndex::GemVersion.new('2.0.0', 'ruby', nil, 'qw2dwe')])]
```

compact_index 0.10.0 had [this code](https://github.com/bundler/compact_index/blob/1256627450de5db45ff0050ba0b13b2366ba095d/lib/compact_index/versions_file.rb#L54-L59) which coalesced all versions in one hash.

**Comment by fotanus** [comment]
Ok, thanks, I understand now. So two ways of fixing this: (1) Getting back the piece of code that unite the strings when creating a file and add a test for that, or (2) do this direcly on bundler-api and rubygems.org. 

Making this on bundler-api or rubygems using SQL seems more efficient, but I'm not sure that this is a price we want to pay. @segiddins what do you think?

**Comment by sonalkr132** [comment]
We won't have to use SQL on server side. We can use:
```Ruby
    gems_hash = {}
    gems.each do |gem|
      gems_hash[gem['name']] ||= []
      gems_hash[gem['name']] << CompactIndex::GemVersion.new(
                                  gem['number'],
                                  gem['platform'],
                                  nil,
                                  gem['info_checksum']
                                )
    end

    gems_hash.map do |name, versions|
      CompactIndex::Gem.new(name, versions)
    end
```

**Comment by fotanus** [comment]
If we are doing this on both rubygems.org and on bundler-api, I think it is better to move this code to compact index? The gem is supposed to avoid duplication on both sides but to not touch the databases directly.

**Comment by sonalkr132** [comment]
> If we are doing this on both rubygems.org and on bundler-api

I don't think bundler-api is maintained anymore.
I believe purpose of adding that array was that all versions of a gem should be together and correct format is following:
```Ruby
CompactIndex::Gem.new("gem2", [
   build_version(:name => "gem2", :number => "1.0.1"),
   build_version(:name => "gem2", :number => "1.0.2", :platform => "arch")])
```

If we do it on server side then the dynamic part of versions response will also be sorter because of lesser duplicates.

**Comment by sonalkr132** [comment]
This is not needed after all. `create` function can be used to update `versions.list`, we would just have to pass the input in correct format.
